spring.application.name=OnlineFoodOrdering
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
server.port=${PORT:8080}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.servlet.session.cookie.same=strict
spring.datasource.url=${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.data.show-sql=true
logging.level.org.springframework.security=DEBUG
stripe.api.key=${STRIPE_KEY}