spring.application.name=OnlineFoodOrdering
cloudinary.cloud-name=
cloudinary.api-key=
cloudinary.api-secret=
jwt.secret=MyVeryStrongSecretKeyThatIsAtLeast32CharsLong
jwt.expiration=86400000
server.port=${PORT:8080}
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
server.servlet.session.cookie.same=strict
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlineFoodOrdering
spring.datasource.username= postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.data.show-sql=true
logging.level.org.springframework.security=DEBUG
stripe.api.key=